name: Deploying
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: print
        run: echo $GITHUB_RUN_NUMBER
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY.M.DD
      - name: set build number to ENV
        run: |
          echo "::set-output name=GIT_COMMIT_NUMBER::$(git rev-list --count HEAD ^master)"
        id: build
      - name: print
        run: |
          echo ${{ steps.build.outputs.GIT_COMMIT_NUMBER }}