name: Deploying
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY.M.DD
      - name: build number
        run: |
        echo 'BUILD_NUMBER<<EOF' >> $GITHUB_ENV
        git rev-list --count master >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
      - name: Checkout repository
        run: echo $BUILD_NUMBER