name: Testing
on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    name: Testing to get build number
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          token: ${{ secrets.GITHUB_TOKENN }}
      - name: Get latest tag
        run: |
          echo "::set-output name=LATEST_TAG_NUMBER::$(git describe --tags `git rev-list --tags --max-count=1`)"
        id: tags
      - name: Get commits count
        run: |
          echo "::set-output name=GIT_COMMIT_NUMBER::$(git rev-list --count master)"
        id: commits
      - name: print version and build
        run: |
          echo "j test"
          echo "${{steps.commits.outputs.GIT_COMMIT_NUMBER}}"
      - name: Set Version and Build number
        uses: yanamura/ios-bump-version@v1
        with:
          version: ${{steps.tags.outputs.LATEST_TAG_NUMBER}}
          build-number: ${{steps.commits.outputs.GIT_COMMIT_NUMBER}}
          project-path: ./MapKitAndCoreLocation.xcodeproj
      - name: update
        run: |
          git add .
          git commit -m "bump version"
          git push origin HEAD