name: Testing
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Testing to get build number
    runs-on: macOS-latest
    steps:
      - name: Get current date
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY.M.DD
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          token: ${{ secrets.GITHUB_TOKENN }}
      - name: set build number
        run: |
          echo "::set-output name=GIT_COMMIT_NUMBER::$(git rev-list --count master)"
        id: commits
      - name: print
        run: |
          echo "${{steps.commits.outputs.GIT_COMMIT_NUMBER}}"
      - name: Set Version and Build number
        uses: yanamura/ios-bump-version@v1
        with:
          version: "${{steps.current-time.outputs.formattedTime}}"
          build-number: "${{steps.commits.outputs.GIT_COMMIT_NUMBER}}"
      - name: update
        run: |
          git add .
          git commit -m "bump version"
          git push origin HEAD