name: Deploying
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: print
        run: echo $GITHUB_RUN_NUMBER
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY.M.DD
      - name: set build number to ENV
        run: |
          GIT_COMMIT_NUMBER=$(git rev-list --count master)
          echo $GIT_COMMIT_NUMBER
          echo ${{ GIT_COMMIT_NUMBER }}
          echo ${GIT_COMMIT_NUMBER}
      - name: print
        run: |
          echo $GIT_COMMIT_NUMBER
          echo ${{ GIT_COMMIT_NUMBER }}
          echo ${GIT_COMMIT_NUMBER}