name: Deploying
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY.M.DD
      - name: Get number of commits
        env:
          commitnumber: $(git rev-list --count master)
      - name: Checkout repository
        run: echo $commitnumber