name: Testing
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Testing to get build number
    runs-on: macOS-latest
    steps:
      - name: print
        run: echo $GITHUB_RUN_NUMBER
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKENN }}
      - name: set build number
        run: |
          echo "::set-output name=GIT_COMMIT_NUMBER::$(git rev-list --count master)"
        id: build
      - name: print
        run: |
          echo "J${{ steps.build.outputs.GIT_COMMIT_NUMBER }}J"
      - name: update
        run: |
          git add .
          git commit -m "bump version"
          git push origin HEAD